spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/Lab1
        username: postgres
        password: 7369


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    sql:
        init:
            mode: always
            data-locations: classpath:data.sql
            schema-locations: classpath:schema.sql